# Generated by Django 4.2.25 on 2025-11-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
