# Generated by Django 4.2.25 on 2025-11-02 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_documentinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAiSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('summary_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_summaries_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
