# Generated by Django 4.2.25 on 2025-11-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='summary_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
